# Generated by Django 3.1.3 on 2021-06-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('photo', models.ImageField(upload_to='myimage')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('Brand', models.CharField(max_length=50)),
                ('OS', models.FloatField()),
                ('cMainCamera', models.IntegerField()),
                ('cRAM', models.IntegerField()),
                ('cCPU', models.CharField(max_length=50)),
                ('cGPU', models.CharField(max_length=50)),
                ('cBattery', models.CharField(max_length=50)),
                ('Dimensions', models.CharField(max_length=50)),
                ('Weight', models.CharField(default=None, max_length=500)),
                ('SIM', models.CharField(default=None, max_length=500)),
                ('Colors', models.CharField(default=None, max_length=500)),
                ('CPU', models.CharField(default=None, max_length=500)),
                ('Chipset', models.CharField(default=None, max_length=500)),
                ('GPU', models.CharField(default=None, max_length=500)),
                ('Technology', models.CharField(default=None, max_length=500)),
                ('Size', models.CharField(default=None, max_length=500)),
                ('Resolution', models.CharField(default=None, max_length=500)),
                ('Builtin', models.CharField(default=None, max_length=500)),
                ('Card', models.CharField(default=None, max_length=500)),
                ('Main', models.CharField(default=None, max_length=500)),
                ('Features', models.CharField(default=None, max_length=500)),
                ('Front', models.CharField(default=None, max_length=500)),
                ('WLAN', models.CharField(default=None, max_length=500)),
                ('Bluetoth', models.CharField(default=None, max_length=500)),
                ('Data', models.CharField(default=None, max_length=500)),
                ('Games', models.CharField(default=None, max_length=500)),
                ('Capacity', models.CharField(default=None, max_length=500)),
            ],
        ),
    ]
