# Generated by Django 3.1.3 on 2021-06-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210627_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('image', models.CharField(max_length=500, unique=True)),
                ('price', models.CharField(max_length=500)),
                ('brand', models.CharField(max_length=50)),
                ('OS', models.CharField(max_length=500)),
                ('cMainCamera', models.CharField(max_length=500)),
                ('cRAM', models.CharField(max_length=500)),
                ('cCPU', models.CharField(max_length=50)),
                ('cGPU', models.CharField(max_length=50)),
                ('cBattery', models.CharField(max_length=500)),
            ],
        ),
    ]
