# Generated by Django 3.1.3 on 2021-06-27 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210627_1814'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='cMobile',
        ),
    ]
