# Generated by Django 3.1.3 on 2021-06-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210627_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmobile',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
