# Generated by Django 3.1.3 on 2021-06-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210627_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmobile',
            name='link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cmobile',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
