# Generated by Django 3.1.3 on 2021-06-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210628_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmobile',
            name='OS',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cmobile',
            name='brand',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cmobile',
            name='cBattery',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cmobile',
            name='cMainCamera',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cmobile',
            name='cRAM',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cmobile',
            name='price',
            field=models.IntegerField(),
        ),
    ]
