# Generated by Django 3.1.3 on 2021-06-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210628_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmobile',
            name='brand',
            field=models.CharField(max_length=500),
        ),
    ]
